pairs = [
    ["old text 1", "new text 1"],
    ["foo", "bar"]
]
case_sensitive = true # defaults to true

# Ignore Configuration
[ignore]
files = ["config.toml", "ignore_this.txt"] # config.toml is ignored by default
directories = ["ignore_dir"]
patterns = ["*.ignore"]
