pairs = [ # Must be present.
    ["old text 1", "new text 1"],
    ["foo", "bar"]
]

case_sensitive = true # defaults to true

# Ignore Configuration
ignore = [".git", "dist", ".env", "ignore_this.txt", "*.ignore"]